from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel
from typing import List
import numpy as np
import joblib
import os
import json

app = FastAPI(
    title="Intelligent IDS API",
    description="Real-time intrusion detection using Machine Learning",
    version="1.0.0"
)

MODEL_PATH = "models/random_forest.pkl"
METRICS_PATH = "models/metrics.json"   # generated by evaluation.py (see below)

if os.path.exists(MODEL_PATH):
    model = joblib.load(MODEL_PATH)
    print("✅ Model loaded")
else:
    model = None
    print("⚠️  Model not found — running in demo mode")


# ── Serve the dashboard HTML ─────────────────────────────────────
@app.get("/")
def serve_dashboard():
    if os.path.exists("ids_dashboard.html"):
        return FileResponse("ids_dashboard.html", media_type="text/html")
    return {"message": "Intelligent IDS API is running", "status": "ok"}


# ── Serve model images (confusion matrix, ROC, SHAP) ────────────
@app.get("/models/{filename}")
def serve_model_file(filename: str):
    path = f"models/{filename}"
    if os.path.exists(path):
        return FileResponse(path)
    return JSONResponse({"error": "File not found"}, status_code=404)


# ── Health check ─────────────────────────────────────────────────
@app.get("/health")
def health():
    return {
        "model_loaded": model is not None,
        "n_features": int(model.n_features_in_) if model else None
    }


# ── Real metrics from training ───────────────────────────────────
@app.get("/metrics")
def get_metrics():
    """
    Returns real evaluation results saved by evaluation.py.
    Falls back to demo values if metrics.json doesn't exist yet.
    """
    if os.path.exists(METRICS_PATH):
        with open(METRICS_PATH) as f:
            return json.load(f)

    # Fallback demo data (replaced once you run train.py)
    return {
        "models": {
            "logistic_regression": {"accuracy": 96.2, "precision": 96.1, "recall": 96.2, "f1": 96.0, "auc": 98.4},
            "random_forest":       {"accuracy": 99.85,"precision": 99.84,"recall": 99.85,"f1": 99.84,"auc": 99.99},
            "mlp":                 {"accuracy": 99.41,"precision": 99.40,"recall": 99.41,"f1": 99.39,"auc": 99.97}
        },
        "best_model": "random_forest",
        "dataset": {
            "total": 100000,
            "benign": 55800,
            "attack": 44200,
            "train_size": 77600,
            "test_size": 19400
        },
        "cv_scores": [99.81, 99.84, 99.79, 99.82, 99.77],
        "confusion_matrix": {"tp": 8370, "fp": 17, "fn": 12, "tn": 11001},
        "note": "demo_values — run train.py to generate real metrics.json"
    }


# ── Predict endpoint ─────────────────────────────────────────────
class InputData(BaseModel):
    features: List[float]


@app.post("/predict")
def predict(data: InputData):
    features = np.array(data.features).reshape(1, -1)

    if model is not None:
        EXPECTED = model.n_features_in_
        if features.shape[1] < EXPECTED:
            features = np.pad(features, ((0, 0), (0, EXPECTED - features.shape[1])))
        elif features.shape[1] > EXPECTED:
            features = features[:, :EXPECTED]

        prediction = model.predict(features)[0]
        probabilities = model.predict_proba(features)[0]
        confidence = float(max(probabilities))
        is_attack = str(prediction).upper() != "BENIGN"
        result = "Attack Detected" if is_attack else "Benign Traffic"
    else:
        score = float(np.mean(np.abs(features)))
        is_attack = score > 0.3
        confidence = 0.9
        result = "Attack Detected (demo)" if is_attack else "Benign Traffic (demo)"

    return {
        "prediction": result,
        "is_attack": is_attack,
        "confidence": round(confidence, 4)
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=False)